# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        mini:
            quality: 50
            filters:
                thumbnail: { size: [ 50, 50 ], mode: outbound }
        small:
            jpeg_quality: 50
            png_compression_level: 5
            filters:
                thumbnail: { size: [ 150, 150 ], mode: inset }
                background: { color: '#FFFFFF' }
        large:
            quality: 75
            filters:
                thumbnail: { size: [ 800, 600 ], mode: inset }
                interlace: #Establecer carga progresiva en la imagen
                    mode: line
                background: { color: '#00FFFF' }
