parameters:
    locale: es
    app_locales: es|en
    default_results_per_page: { '10': 10,'25': 25, '100': 100, '1000': 1000 }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    SocialApp\Apps\Salud\Webapp\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    CarlosChininin\App\Domain\Model\AuthMenu\MenuServiceInterface: '@SocialApp\Apps\Salud\Webapp\Service\Menu\MenuService'
    CarlosChininin\ApiSearchPerson\SearchPersonService: ~
